---
- hosts: localhost
  tasks:
    - name: Pull Docker image from Docker Hub
      shell: docker pull sankalp137rai/calculator_java:latest

    - name: Run Docker container
      shell: docker run -d -p 8081:8080 sankalp137rai/calculator_java:latest
